name: Docker Images for PHP 8

on:
  push:
    branches:
      - main
    paths:
      - docker/Dockerfile
      - .github/workflows/docker-8.yml

env:
  IMAGE_REPO: "dbor91/apache2-php"

jobs:
  "PHP-8_0":
    runs-on: ubuntu-latest
    env: 
      IMAGE_VERSION: "8.0"
    steps:
      - uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build Images
        run: bash bin/build-image

      - name: Push
        run: docker push $IMAGE_REPO:$IMAGE_VERSION

  "PHP-8_1":
    runs-on: ubuntu-latest
    env:
      IMAGE_VERSION: "8.1"
    steps:
      - uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build Images
        run: bash bin/build-image

      - name: Push
        run: docker push $IMAGE_REPO:$IMAGE_VERSION

  "PHP-8_2":
    runs-on: ubuntu-latest
    env:
      IMAGE_VERSION: "8.2"
    steps:
      - uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build Images
        run: bash bin/build-image

      - name: Push
        run: docker push $IMAGE_REPO:$IMAGE_VERSION

  "PHP-8_3":
    runs-on: ubuntu-latest
    env:
      IMAGE_VERSION: "8.3"
    steps:
      - uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build Images
        run: bash bin/build-image

      - name: Push
        run: docker push $IMAGE_REPO:$IMAGE_VERSION

  "PHP-8_4":
    runs-on: ubuntu-latest
    env:
      IMAGE_VERSION: "8.4"
    steps:
      - uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build Images
        run: bash bin/build-image

      - name: Push
        run: docker push $IMAGE_REPO:$IMAGE_VERSION

